### ISSUE TITLE
add_signature method not working

### ISSUE THREAD

**Issue by ciroartz** [michaelhly/solana-py#181]
Hello, I have a ts code that works fine when I try to do: `transaction.addSignature(notary, bs58.decode(sigStr));` 

On python on the other hand, it's returning: 

```
Traceback (most recent call last):
  File "c:\Users\Downloads\Solana\Solana\test.py", line 260, in <module>
    asyncio.run(test())
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\Users\Downloads\Solana\Solana\me_launchpad.py", line 254, in test
    tx_instructions.add_signature(pubkey=PublicKey(infos.notary), signature=base58.b58decode(str(sig_str)))
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\solana\transaction.py", line 271, in add_signature
    raise ValueError("unknown signer: ", str(pubkey))
ValueError: ('unknown signer: ', 'A8b43w4efa2G6T4pQR9Hif8nj5A3ow2bnx6dAzYJBffP')
```

I am 99% sure that the my python code and the ts codes are 1:1 and this is the last step needed for my transaction. 

I previously add the `infos.notary` as a signer through anchorpy like this: 

`remAccounts.append(AccountMeta(pubkey=PublicKey(infos.notary), is_signer=True, is_writable=False))`

Yet when I try to add a signature it gives that first error. 

Could you please help me out?

I'm currently using the latest version of both, solanapy and anchorpy. Python version is 3.9.10

**Comment by ciroartz** [comment]
#182 Error was due to this, could you please take a look?
