### ISSUE TITLE
CreateAccountWithSeedParams error or not aligned with docs

### ISSUE THREAD

**Issue by jacekv** [michaelhly/solana-py#214]
Hey there :)

I have been experimenting with your lib and it works pretty well. Yet, I found a problem with the `CreateAccountWithSeedParams` tuple. According to the docs, the seed should be of type str, see [here](https://michaelhly.github.io/solana-py/core/system_program/#solana.system_program.CreateAccountWithSeedParams)

While using the tuple and providing a string as seed I get the following error:
`ValueError: not enough values to unpack (expected 2, got 1)`

It turns out that I have to provide a dict in the following form: `seed={"length": len(seed), "chars": seed},`

There are two possibilities:
  1) We update the docs
  2) We fix it in the code. If str given, transform to dict. If dict given and contains both keys, great :)

What would you prefer?

**Comment by kevinheavey** [comment]
Can you provide a code sample? I can't reproduce this error

**Comment by jacekv** [comment]
Sure, here is an entire piece of code:

```Python
import yaml
import json
from os import path
from solana.rpc.api import Client
from solana.keypair import Keypair
from solana.publickey import PublicKey
from solana.transaction import Transaction, TransactionInstruction
from solana.system_program import create_account_with_seed, CreateAccountWithSeedParams

client = None
payer = None
greeted_public_key = None
program_id = None

LAMPORTS_PER_SOL = 1000_000_000


def getConfig():
    config_path = path.normpath(path.join(path.expanduser('~'), '.config', 'solana', 'cli', 'config.yml'))
    with open(config_path, 'r') as f:
        try:
            config = yaml.load(f, Loader=yaml.FullLoader)
        except FileNotFoundError as fnfe:
            print(fnfe)
            print('Please setup solana-cli config first')
            sys.exit(1)
    return config

def getRpcUrl():
    config = getConfig()
    if 'json_rpc_url' in config:
        return config['json_rpc_url']
    print("Failed to read RPC url from config file. Falling back to localhost")
    return "http://127.0.0.1:8899"

def getPayer():
    """
    Tries to read the secret key from the file referenced in the config file. If no file is found, a new keypair is generated.
    """
    config = getConfig()
    if 'keypair_path' in config:
        with open(config['keypair_path'], 'rb') as f:
            keypair = Keypair.from_secret_key(b"".join(map(lambda x: x.to_bytes(1, "big"), json.loads(f.read().decode('utf-8')))))
            return keypair
    print('Failed to create keypair from cli, falling back to new random keypair')
    keypair = Keypair()
    return Keypair()


def establishConnection():
    """
    Establishes a connection to the Solana cluster.
    """
    global client

    rpc_url = getRpcUrl()
    try:
        client = Client(rpc_url)
    except Exception as e:
        print(e)
        print("Failed to establish connection to RPC server")
        sys.exit(1)

def establishPayer():
    global payer

    fees = 0

    feeCalculator = client.get_recent_blockhash()["result"]["value"]["feeCalculator"]

    fees += client.get_minimum_balance_for_rent_exemption(1)["result"]

    fees += feeCalculator["lamportsPerSignature"] * 100

    payer = getPayer()

    balance = client.get_balance(payer.public_key)["result"]["value"]
    print(f"Balance for {payer.public_key} is {balance} lamports")

    if balance < fees:
        print("Not enough balance on account. Going to request an airdrop")
        tx = client.request_airdrop(payer.public_key, 2 * LAMPORTS_PER_SOL)

        print('Waiting for transaction to be finalized...')
        client.confirm_transaction(tx["result"])

        balance = client.get_balance(payer.public_key)["result"]["value"]
        print(f"Balance for {payer.public_key} is {balance} lamports")
   

if __name__ == '__main__':
    establishConnection()
    establishPayer()
    lamports = client.get_minimum_balance_for_rent_exemption(1)["result"]

    program_id = Keypair().public_key
    test_seed = "hello"
    greeted_public_key = PublicKey.create_with_seed(payer.public_key, test_seed, program_id)

    transaction = Transaction().add(
        create_account_with_seed(CreateAccountWithSeedParams(
            from_pubkey=payer.public_key,
            base_pubkey=payer.public_key,
            #seed={"length": len(test_seed), "chars": test_seed},
            seed=test_seed,
            new_account_pubkey=greeted_public_key,
            lamports=lamports,
            space=1,
            program_id=program_id
        ))
    )
    tx = client.send_transaction(transaction, payer)
    client.confirm_transaction(tx["result"])
```

I had to install following packages:
`pip install solana pyyaml `

I am running a local test validator:
`solana-test-validator`

That's why I am reading the key and url in. If you need more details, let me know :)

Once I run this code, I get the following error:

```
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    create_account_with_seed(CreateAccountWithSeedParams(
  File "/Users/jacek.varky/project/solana/Solana-Intro/PR_code/venv/lib/python3.8/site-packages/solana/system_program.py", line 491, in create_account_with_seed
    data = SYSTEM_INSTRUCTIONS_LAYOUT.build(
  File "/Users/jacek.varky/project/solana/Solana-Intro/PR_code/venv/lib/python3.8/site-packages/construct/core.py", line 336, in build
    self.build_stream(obj, stream, **contextkw)
  File "/Users/jacek.varky/project/solana/Solana-Intro/PR_code/venv/lib/python3.8/site-packages/construct/core.py", line 348, in build_stream
    self._build(obj, stream, context, "(building)")
  File "/Users/jacek.varky/project/solana/Solana-Intro/PR_code/venv/lib/python3.8/site-packages/construct/core.py", line 2144, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/Users/jacek.varky/project/solana/Solana-Intro/PR_code/venv/lib/python3.8/site-packages/construct/core.py", line 2657, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/Users/jacek.varky/project/solana/Solana-Intro/PR_code/venv/lib/python3.8/site-packages/construct/core.py", line 3924, in _build
    return sc._build(obj, stream, context, path)
  File "/Users/jacek.varky/project/solana/Solana-Intro/PR_code/venv/lib/python3.8/site-packages/construct/core.py", line 2144, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/Users/jacek.varky/project/solana/Solana-Intro/PR_code/venv/lib/python3.8/site-packages/construct/core.py", line 2657, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/Users/jacek.varky/project/solana/Solana-Intro/PR_code/venv/lib/python3.8/site-packages/construct/core.py", line 2133, in _build
    context.update(obj)
  File "/Users/jacek.varky/project/solana/Solana-Intro/PR_code/venv/lib/python3.8/site-packages/construct/lib/containers.py", line 117, in update
    for k,v in seqordict:
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by michaelhly** [comment]
@jacekv I think this issue was fixed here:
https://github.com/michaelhly/solana-py/commit/21228ef9ace459d06b294d8f5919f6a165f779b3

@kevinheavey would you mind creating a patch release?

**Comment by kevinheavey** [comment]
https://github.com/michaelhly/solana-py/pull/215#issuecomment-1084976583
