### ISSUE TITLE
get_token_accounts_by_owner throws exception

### ISSUE THREAD

**Issue by DanKamilov** [michaelhly/solana-py#276]
Hello. Today .get_token_accounts_by_owner() started throws exception 

`Traceback (most recent call last):
  File "venv/lib/python3.7/site-packages/solana/exceptions.py", line 35, in argument_decorator
    return func(*args, **kwargs)
  File "venv/lib/python3.7/site-packages/solana/rpc/providers/http.py", line 24, in make_request
    return self._after_request(raw_response=raw_response, method=method)
  File "venv/lib/python3.7/site-packages/solana/rpc/providers/core.py", line 54, in _after_request
    raw_response.raise_for_status()
  File "venv/lib/python3.7/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.mainnet-beta.solana.com/

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 97, in <module>
    balanceHLT = client.get_token_accounts_by_owner(sender.public_key, TokenAccountOpts(program_id=TOKEN_PROGRAM_ID, encoding="jsonParsed"))
  File "venv/lib/python3.7/site-packages/solana/rpc/api.py", line 1115, in get_token_accounts_by_owner
    return self.__get_token_accounts(*args)
  File "venv/lib/python3.7/site-packages/solana/rpc/api.py", line 1125, in __get_token_accounts
    return self._provider.make_request(*args)
  File "venv/lib/python3.7/site-packages/solana/exceptions.py", line 37, in argument_decorator
    raise internal_exception_cls(exc, func, *args, **kwargs) from exc
solana.exceptions.SolanaRpcException`

**Comment by michaelhly** [comment]
This is b/c the Solana node is down.
