### ISSUE TITLE
Keypair-pubkey mismatch Python when partial signing

### ISSUE THREAD

**Issue by RamirezAlex** [michaelhly/solana-py#279]
I am trying to create and partial sign a transaction for create an account, but I keep receiving a keypair mismatch error. My code looks like this:

```
from spl.token.instructions import create_associated_token_account
from solana.keypair import Keypair
from solana.publickey import PublicKey
from solana.transaction import Transaction

signer = Keypair()

create_transaction_instruction = create_associated_token_account(
    payer=PublicKey(mintFeePayer), owner=signer.public_key, mint=PublicKey(mintPublicKey)
)

transaction = Transaction()
transaction.add(
    create_transaction_instruction
)

transaction.sign_partial(signer)
```

And I always get:

```
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "kinetic_sdk/__main__.py", line 49, in <module>
    transaction.sign_partial(signer)
  File "/Users/alexramirez/Library/Caches/pypoetry/virtualenvs/kinetic-sdk--u4hmztD-py3.8/lib/python3.8/site-packages/solana/transaction.py", line 299, in sign_partial
    self._solders.partial_sign(underlying_signers, self._solders.message.recent_blockhash)
solders.SignerError: keypair-pubkey mismatch
make: *** [run_sdk] Error 1
```

I am not sure, it is worth mention, but I have almost the same code running in TypeScript and it is doing the signing well.

Thanks.

**Comment by kusiev** [comment]
got same issue...

**Comment by michaelhly** [comment]
cc @kevinheavey

**Comment by kevinheavey** [comment]
@RamirezAlex this tx needs to be signed by the `payer`, not the `owner`.

**Comment by michaelhly** [comment]
Related to https://github.com/michaelhly/solana-py/issues/268

**Comment by kevinheavey** [comment]
Think this one is just the payer/owner thing

**Comment by beeman** [comment]
Hey there @kevinheavey, we did some more research on what we are after with the partial signing. The main difference with [your answer here](https://gist.github.com/beeman/97727ddee851d2b9b72b3bb5b88d0623) is in our app the fee payer is on a remote api.

The flow is something like so:

- owner generates keypair.
- owner creates a create token account transaction, setting the remote fee payer as the signer.
- partially signs the transaction.
- serialize the transaction and submit to the API.
- the api deserializes the transaction
- the api partially signs it
- the api sends the transaction to Solana


I built a [simplified demo in TypeScript](https://gist.github.com/beeman/97727ddee851d2b9b72b3bb5b88d0623) that shows what we are aiming to do. Note in this example how the `Transaction` constructor accepts a `signatures` array where we add the `null` signature for the owner. 


```python
from solana.keypair import Keypair
from solana.publickey import PublicKey
from solana.transaction import Transaction

owner = Keypair()
signer = Keypair()

# note, here we only have the signer pubkey
create_transaction_instruction = create_associated_token_account(
    payer=signer.pubkey, owner=owner.pubkey, mint=PublicKey(mint_pubkey)
)

transaction = Transaction()
transaction.add(
    create_transaction_instruction
)

# This is where the owner signs
transaction.sign_partial(owner)

# serialize to send partially signed tx over the wire
serialized_transaction = transaction.serialize()

# De-serialize it on the remote side
# received = Transaction.deserialize(serialized_transaction)

# Partial sign it with the remote_fee_payers' keypair
received.sign_partial(signer)

# Send the raw transaction
tx = client.send_raw_transaction(received.serialize())
```

It would be great if you could see if this is something that solana-py could support, from looking at some other issues it seems like a pretty common feature and would be nice to have the same feature as we have in TypeScript!

**Comment by kevinheavey** [comment]
@beeman does this not work?

```python
from solana.keypair import Keypair
from solana.publickey import PublicKey
from solana.transaction import Transaction, TransactionInstruction
from spl.token.instructions import (
    create_associated_token_account,
    set_authority,
    get_associated_token_address,
    AuthorityType,
    SetAuthorityParams,
)
from spl.token.constants import TOKEN_PROGRAM_ID
from solders.hash import Hash

REMOTE_FEE_PAYER_KEYPAIR = Keypair.from_secret_key(
    bytes(
        [
            251,
            250,
            215,
            164,
            5,
            65,
            45,
            223,
            129,
            110,
            254,
            210,
            136,
            194,
            238,
            45,
            179,
            49,
            42,
            41,
            49,
            110,
            170,
            53,
            205,
            72,
            220,
            13,
            169,
            152,
            130,
            155,
            210,
            143,
            171,
            12,
            86,
            21,
            178,
            27,
            134,
            179,
            155,
            149,
            210,
            81,
            140,
            224,
            169,
            110,
            26,
            52,
            198,
            149,
            69,
            164,
            147,
            12,
            14,
            86,
            85,
            75,
            136,
            253,
        ]
    )
)

fee_payer = REMOTE_FEE_PAYER_KEYPAIR.public_key
owner = Keypair()
mint = PublicKey("KinDesK3dYWo3R2wDk6Ucaf31tvQCCSYyL8Fuqp33GX")
associated_token_account = get_associated_token_address(mint, owner.public_key)
instructions: list[TransactionInstruction] = [
    create_associated_token_account(fee_payer, owner.public_key, mint),
    set_authority(
        SetAuthorityParams(
            program_id=TOKEN_PROGRAM_ID,
            account=associated_token_account,
            current_authority=owner.public_key,
            authority=AuthorityType.CLOSE_ACCOUNT,
            new_authority=fee_payer,
        )
    ),
]
blockhash = str(Hash.default())
transaction = Transaction(recent_blockhash=blockhash, fee_payer=fee_payer, instructions=instructions)
transaction.sign_partial(owner)
serialized = transaction.serialize(verify_signatures=False)
received = Transaction.deserialize(serialized)
received.sign_partial(REMOTE_FEE_PAYER_KEYPAIR)
```

**Comment by beeman** [comment]
@kevinheavey I think we're getting a step further as I'm now getting another error:

> #2Token Program Instruction
> Program logged: "Instruction: SetAuthority"
> Program logged: "Error: InvalidArgument"
> Program consumed: 1155 of 379511 compute units
> Program returned error: "invalid program argument"

I got a transaction here created by our Python code (following your example):

```
AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADi7V3LzjqxkEkSvG010rPMlF1N1QvJ7wWrXfWJtHSaxRxcWMfrBVHrglfE7D/Xzs5m8qit23836V3iTNxeHZwDAgEFCQvp6+vLFGkhL4yY/QyUSK+N/fJu4W4V03ZXb87Qpr5Ou7+V0BiceAJULIhRFG5y3lwlyHmPocLQbRTdNA7NrkzFd8hm0A3hGqQLpHKvzsSUASCTpxL5ZQ1/PYA3QyK+kuNhZwBjAW62JquMSK/vzmnmDXdDbwhKrR5aISEvHEbgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEy7HnMsSwlWkU6vkCV/diuSqyU/gizZ/W4DeFCV3bDAan1RcZLFxRIYzJTD1K8X9Y2u4Im6H9ROPb2YoAAAAABt324ddloZPZy+FGzut5rBy0he1fWzeROoz1hX7/AKmMlyWPTiSJ8bs9ECkUjg2DC1oTmdr/EIQEjnvY2+n4WXCP1IEtgNF/+N70411+Ltb3cqk/q9WOGpz5f/t/SNLsAggHAAIBBQQHBgAHAgMBIwYDAQvp6+vLFGkhL4yY/QyUSK+N/fJu4W4V03ZXb87Qpr5O
```

For reference, this is what our TypeScript code generates:

```
AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADCy+hNRbUIf/dBh1R72WMw2B+GImFYuoged0RNPtBR0uLfcym7wxezeZB9SR1aPcmEVV4hoNMJanWUiNBCf0kGAgEFCAvp6+vLFGkhL4yY/QyUSK+N/fJu4W4V03ZXb87Qpr5On/rqnKfGr89gaPn/pPRt7jTdI0/lpSNwCkAa4Vx9eu3LJB6MG3N2f2+aM5Sj/I5K2ja3YDv4HC2KRjuLlZvWUwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjJclj04kifG7PRApFI4NgwtaE5na/xCEBI572Nvp+FkEy7HnMsSwlWkU6vkCV/diuSqyU/gizZ/W4DeFCV3bDAan1RcZLFxRIYzJTD1K8X9Y2u4Im6H9ROPb2YoAAAAABt324ddloZPZy+FGzut5rBy0he1fWzeROoz1hX7/AKl7pV7CrQefg7Ug+JPRu6Po1jrtZdsafk1neZT3elngTAIEBwACAQUDBwYABwICASMGAwEL6evryxRpIS+MmP0MlEivjf3ybuFuFdN2V2/O0Ka+Tg==
```

**Comment by kevinheavey** [comment]
@beeman can you check if the serialized `set_authority` instructions are different? I'm guessing this is just a wrong argument to `set_authority` and not a signing issue
