### ISSUE TITLE
Pubkey Type Error

### ISSUE THREAD

**Issue by kasahh** [michaelhly/solana-py#381]
Hello, I tried getting my wallet balance using the get_balance() function but i keep getting the error below and I have no idea why. What am I doing wrong and how can I fix it. Any help is much appreciated. Thanks

```
Traceback (most recent call last):
  File "/Users/kasah/Document/test.py", line 120, in <module>
    balance_check()
  File "/Users/kasah/Document/test.py", line 114, in balance_check
    data = http_client.get_balance(PublicKey, commitment)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/solana/rpc/api.py", line 145, in get_balance
    body = self._get_balance_body(pubkey, commitment)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/solana/rpc/core.py", line 173, in _get_balance_body
    return GetBalance(pubkey, RpcContextConfig(commitment=commitment_to_use))
TypeError: argument 'pubkey': 'str' object cannot be converted to 'Pubkey'
```

**Comment by michaelhly** [comment]
See: https://michaelhly.com/solana-py/rpc/api/#solana.rpc.api.Client.get_balance
