### ISSUE TITLE
Serde JSON error occurs during ratelimited RPC calls?

### ISSUE THREAD

**Issue by neochine** [michaelhly/solana-py#472]
```
Testing endpoint: https://solana-mainnet.g.alchemy.com/v2/Qs..REDACTED...G
Failed to get account info for EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v 
(Traceback (most recent call last):
  File "/root/.../src/solanapy_toolkit/lib/ClientWrapper.py", line 247, in retryable_get_account_info_json_parsed
    account_info = solana_client.get_account_info_json_parsed(address, commitment=commitment)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/solana/rpc/api.py", line 200, in get_account_info_json_parsed
    return self._provider.make_request(body, GetAccountInfoMaybeJsonParsedResp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/solana/exceptions.py", line 45, in argument_decorator
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/solana/rpc/providers/http.py", line 49, in make_request
    return _parse_raw(raw, parser=parser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/solana/rpc/providers/core.py", line 96, in _parse_raw
    parsed = parser.from_json(raw)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^
solders.SerdeJSONError: data did not match any variant of untagged enum Resp
)
```
It used to work few days earlier but now i think RPC got ratelimited and it started throwing errors?
This is my code
```
def test_get_ideal_endpoint():
    endpoints = solanapy_toolkit.get_ideal_endpoints()
    endpoints.extend(["https://api.mainnet-beta.solana.com"])
    for endpoint in endpoints:
        print(f"Testing endpoint: {endpoint}")
        client = solanapy_toolkit.SolanaClient(endpoints=[endpoint])

        # Account Info
        try:
            with timeout(30, RuntimeError):
                account_info = client.retryable_get_account_info_json_parsed('EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v')
                ....
                .... 
        except RuntimeError:
            print(f"Failed to execute account info for {endpoint}")
            continue
```
My solana version is solana==0.35.1

And this is wrapper function
https://codeberg.org/Neochine/solanapy-toolkit/src/branch/master/src/solanapy_toolkit/lib/ClientWrapper.py

**Comment by neochine** [comment]
![2024_11_28_0mm_Kleki](https://github.com/user-attachments/assets/08631542-7af9-4e4e-b6b4-98f9ccd26519)
First call got failed due to serde.JSON error, second retry success

**Comment by neochine** [comment]
A better error would be better I think. like raise RateLimitError instead of serdeJSON error?

**Comment by neochine** [comment]
Closing since its RPC issue and not solanapy
