### ISSUE TITLE
Solana and httpx library version mismatch? Unable to create client

### ISSUE THREAD

**Issue by thedch** [michaelhly/solana-py#481]
```
❯ uv pip freeze | grep -i "solana\|httpx"
httpx==0.23.0
solana==0.36.1
```

```
❯ python
Python 3.11.11 (main, Dec  6 2024, 21:09:50) [Clang 18.1.8 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from solana.rpc.api import Client
>>> Client("https://api.mainnet-beta.solana.com")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daniel/code/crypto/.venv/lib/python3.11/site-packages/solana/rpc/api.py", line 99, in __init__
    self._provider = http.HTTPProvider(endpoint, timeout=timeout, extra_headers=extra_headers, proxy=proxy)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/code/crypto/.venv/lib/python3.11/site-packages/solana/rpc/providers/http.py", line 52, in __init__
    self.session = httpx.Client(timeout=timeout, proxy=proxy)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Client.__init__() got an unexpected keyword argument 'proxy'
```

Is this expected? I freshly installed the libraries and running into this issue. It seems like this library is expecting a specific httpx version, but isn't pinning that version correctly?

**Comment by thedch** [comment]
If anyone else runs into this -- upgrading httpx library fixed it!
