### ISSUE TITLE
AttributeError: transaction has not been signed correctly

### ISSUE THREAD

**Issue by max-block** [michaelhly/solana-py#57]
I'm trying to send SOL from one account to another in testnet:

```python
import os

import base58
from dotenv import load_dotenv
from solana.account import Account
from solana.publickey import PublicKey
from solana.rpc.api import Client
from solana.system_program import TransferParams, transfer
from solana.transaction import Transaction

load_dotenv()

# example: Fy8WpnXAn2UULUEiN2ip4AS5hCAuhJkDApKwjdaWDDkB
from_address = os.getenv("ADDRESS_0")

# example: 5hKkU1C8WhTEvSRxb9GXp8vQLsaPKFVwo8EcdeKm2ZLiCw3TkaP9N4G7tkh84kpD3ER99eZsPqRTgY2rYqWh6AWB
private_key = os.getenv("PRIVATE_0")

# example: 3TrQtmFtAh52MrSUrgHYajMUaMGebFFNCyaNTj3LGx5N
to_address = os.getenv("ADDRESS_1")

client = Client("https://testnet.solana.com")

acc = Account(base58.b58decode(private_key)[:32])
print(acc.public_key().to_base58().decode() == from_address)  # True. I'm sure that private key is valid for from_address

# check from_address balance
res = client.get_balance(acc.public_key())
print("balance", res["result"]["value"] / 10 ** 9)  # 1000.0, I'm sure than from_address has enough SOL

res = client.get_recent_blockhash()
recent_blockhash = res["result"]["value"]["blockhash"]
print("recent_blockhash", recent_blockhash)  # HXacPFu9CHNqPG3LzP43L4EYHtsL3gAvDPNT6CvhjGZK

tx = Transaction(fee_payer=acc.public_key(), recent_blockhash=recent_blockhash)
tx.add(transfer(TransferParams(from_pubkey=PublicKey(from_address), to_pubkey=PublicKey(to_address), lamports=1 * 10 ** 9)))
tx.sign(acc)

res = client.send_transaction(tx)
#  raise AttributeError("transaction has not been signed correctly")
```

It fails with such an error:
```
Traceback (most recent call last):
  File "/Users/max/projects/learn/pypi__solana/t3__transfer_lamports.py", line 39, in <module>
    res = client.send_transaction(tx)
  File "/Users/max/projects/learn/pypi__solana/.venv/lib/python3.9/site-packages/solana/rpc/api.py", line 973, in send_transaction
    return self.send_raw_transaction(txn.serialize(), opts=opts)
  File "/Users/max/projects/learn/pypi__solana/.venv/lib/python3.9/site-packages/solana/transaction.py", line 317, in serialize
    raise AttributeError("transaction has not been signed correctly")
AttributeError: transaction has not been signed correctly
```
What I'm doing wrong?

**Comment by max-block** [comment]
It's my fault. 

It's necessary to pass signers to send_transaction method: `res = client.send_transaction(tx, acc)`

**Comment by krishna-bhandari** [comment]
@max-block  But still I am getting the same error. Is there anything additional to be corrected?

**Comment by Abdulkereem** [comment]
any luck still having same error

**Comment by michaelhly** [comment]
@krishna-bhandari, @Abdulkereem have you guys updated to the latest version?
